-- Fenix Systens CRM v10 — execute in Supabase SQL Editor.
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text, email text unique not null, phone text, role text not null default 'user' check (role in ('admin','user')),
  status text not null default 'pending' check (status in ('pending','authorized','blocked')),
  permissions jsonb not null default '{}'::jsonb, last_seen_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), name text not null, email text, phone text, document text, address jsonb, notes text, source text, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.suppliers (id uuid primary key default gen_random_uuid(), name text not null, document text, email text, phone text, address jsonb, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), name text not null, code text unique, description text, category text, unit text default 'un', cost_price numeric(14,2) default 0, sale_price numeric(14,2) default 0, stock numeric(14,3) default 0, minimum_stock numeric(14,3) default 0, location text, image_url text, supplier_id uuid references public.suppliers(id), created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.inventory_movements (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), type text not null check (type in ('in','out','adjustment')), quantity numeric(14,3) not null, reason text, source_id uuid, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.sales (id uuid primary key default gen_random_uuid(), customer_id uuid references public.customers(id), subtotal numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, total numeric(14,2) not null default 0, payment_method text, status text not null default 'completed', created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.sale_items (id uuid primary key default gen_random_uuid(), sale_id uuid not null references public.sales(id) on delete cascade, product_id uuid not null references public.products(id), quantity numeric(14,3) not null, unit_price numeric(14,2) not null, total numeric(14,2) not null);
create table if not exists public.cash_transactions (id uuid primary key default gen_random_uuid(), type text not null check (type in ('sale','in','out','withdrawal','sangria','opening','closing')), amount numeric(14,2) not null, description text, sale_id uuid references public.sales(id), created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.financial_entries (id uuid primary key default gen_random_uuid(), type text not null check (type in ('income','expense')), description text not null, amount numeric(14,2) not null, category text, payment_method text, due_date date, paid_at timestamptz, status text not null default 'pending', source_id uuid, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), action text not null, module text not null, description text, ip_or_origin text, created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.customers enable row level security; alter table public.suppliers enable row level security; alter table public.products enable row level security; alter table public.inventory_movements enable row level security; alter table public.sales enable row level security; alter table public.sale_items enable row level security; alter table public.cash_transactions enable row level security; alter table public.financial_entries enable row level security; alter table public.audit_logs enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and status='authorized') $$;
create policy "own profile or admin" on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
create policy "authorized users read CRM" on public.customers for select to authenticated using (exists(select 1 from public.profiles where id=auth.uid() and status='authorized'));
create policy "authorized users write CRM" on public.customers for all to authenticated using (exists(select 1 from public.profiles where id=auth.uid() and status='authorized')) with check (exists(select 1 from public.profiles where id=auth.uid() and status='authorized'));
-- Repeat the same authorized-user policy pattern for suppliers, products, movements, sales, sale_items, cash_transactions and financial_entries.
create policy "admin audit read" on public.audit_logs for select to authenticated using (public.is_admin());
create policy "authenticated audit insert" on public.audit_logs for insert to authenticated with check (user_id=auth.uid());
